void f1(int n); 

void test_1(void)
{
    f1(10); 
    int k; 
    k=10; 
    f1(k); 
}

int f2(void)
{
    return 10; 
}

void test_2()
{
    int ret; 

    ret = f2(); 
}

void f3(int* p)
{
    *p = 10; 
}

void test_3(void)
{
    int n; 

    f3(&n); 
}

void swap(int* p1, int* p2)
{
    int tmp; 

    tmp = *p1; 

}

////////////////////////////////////////////

void f4(int** pp)
{
    int* addr; 
    // addr <- address generated by f4() 

    *pp = addr; 
}

void test_4()
{
    int* p = 0; 

    f4(&p); 
}

void get_last_node(list_t* p_list, node_t** pp_node)
{
    node_t* addr; 
    /* Compute and make sure that addr contains the 
    address of last node */

    *pp_node = addr; 
}

void insert_end(list_t* p_list, data_t new_data)
{ 
    node_t* p_last_node = 0; 

    get_last_node(p_list, &p_last_node); 
}


int main(void)
{
    list_t* p_list = create_list(); 

    insert_end(p_list, 10); 
}

int* get_int(int new_val)
{
    int* p = NULL; 

    p = (int*)malloc(sizeof(int)); 
    assert(p != NULL); 

    *p = new_val; 

    return (p); 
}

void test_get_int(void)
{
    int* p = get_int(10); 

    free(p); 

    FILE* fp = fopen("abc.txt", "r"); 

    fclose(fp); 
    fp = NULL; 
}

FILE* fopen(const char* path_name, const char* mode)
{
    static FILE instance_file; 

    return &instance_file; 
}

///////////////////////////////////////////////

int main(void)
{
    int* p = NULL; 

    get_int(&p, 10); 

    int m = *p; 

    free(p); 
    p = NULL; 

}

void get_int(int** pp, int new_val)
{
    int* p = NULL; 

    p = (int*)malloc(sizeof(int)); 
    assert(p); 
    *p = new_val; 

    *pp = p; 
}

int main(void)
{
    int* p_arr = NULL; 
    size_t N = 0; 

    get_array(&p_arr, &N); 
}

void get_array(int** pp_arr, size_t* pN)
{
    int* p_arr = NULL; 
    size_t N; 

    printf("Enter size:"); 
    scanf("%llu", &N); 

    p_arr = (int*)calloc(N, sizeof(int)); 
    assert(p_arr); 

    // populate p_arr[0] to p_arr[N-1] with some data 

    *pp_arr = p_arr; 
    *pN = N; 
}

// b